version: '3.8'

services:
  app:
    build:
      context: ./t_api
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=tradein
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - ./t_api:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./t_frontend
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tradein
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306

  # artisan:
  #   build:
  #     context: ./t_api
  #   container_name: laravel_artisan
  #   entrypoint: ["php", "/var/www/artisan", "app:import-json-feed"]
  #   depends_on:
  #     - db

